version: '2.4'
 
services:
  globalprotect:
    image: globalprotect-docker
    hostname: globalprotect
    restart: unless-stopped
    tty: true
    volumes:
      - ./config/com.yuezk.qt:/root/.config/com.yuezk.qt
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 127.0.0.1:8083:8083
      - 127.0.0.1:8080:1080
    networks:
      - globalprotect
    environment:
      - QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox
 
networks:
  globalprotect:
    external: false
    name: globalprotect
